"""
Delta Permutation Test — Incremental Value of News Beyond AR
=============================================================

Tests whether news features provide statistically significant improvement
BEYOND the autoregressive baseline, by comparing the observed delta
  delta_obs = PR-AUC(AR+News) - PR-AUC(AR-only)
to a null distribution of deltas generated by shuffling the temporal
ordering of news features within each district × fold.

This answers the primary paper question: does news add value given AR?
The temporal shuffle test (04_temporal_shuffle_test.py) only tests news
in isolation; this test conditions on AR performance.

METHODOLOGY:
  For each of N_PERMUTATIONS permutations:
    1. For each fold, recompute fold-aware z-scores (leakage-free, identical
       to 01_train_models.py).
    2. Shuffle news feature columns within each district's rows (destroys
       temporal alignment, preserves marginal distribution).
    3. Train both AR-only and Combined (AR + shuffled news) models.
    4. Record delta = Combined PR-AUC - AR PR-AUC for this permutation.
  The observed delta from 01_train_models.py is compared to this null
  distribution to obtain a p-value.

OUTPUTS:
  results/delta_permutation_test/
    null_delta_distribution.csv  -- N rows: permutation_id, mean_delta, fold deltas
    config.json                  -- run configuration + p-value
"""

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from catboost import CatBoostClassifier, Pool
from sklearn.metrics import average_precision_score

warnings.filterwarnings("ignore")


# ============================================================================
# CONFIGURATION
# ============================================================================

class DeltaTestConfig:
    BASE_DIR     = Path(__file__).parent
    DATA_DIR     = BASE_DIR / "DATA"
    DATA_FILE    = DATA_DIR / "dataset.parquet"
    MONTHLY_FILE = DATA_DIR / "modelling" / "monthly_gdelt_features.parquet"
    FILTER_FILE  = DATA_DIR / "filtering" / "strict_filtered_districts.csv"
    RESULTS_DIR  = BASE_DIR / "results" / "delta_permutation_test"

    REAL_RESULTS_FILE = BASE_DIR / "results" / "window_2yr" / "fold_results.csv"

    N_PERMUTATIONS      = 100
    TRAIN_WINDOW_MONTHS = 20
    IPC_PERIOD_MONTHS   = 4
    MONTHLY_DATA_START  = pd.Timestamp("2021-01-01")
    VALIDATION_FRACTION = 0.20

    AR_FEATURES = ["ipc_lag_1", "ipc_persistence_2yr", "spatial_lag", "ipc_period"]
    NEWS_THEMES = [
        "conflict", "displacement", "economic", "food_security",
        "governance", "health", "humanitarian", "weather", "other",
    ]
    NEWS_FEATURES     = [f"{t}_relative_coverage" for t in NEWS_THEMES] + [f"{t}_zscore" for t in NEWS_THEMES]
    COMBINED_FEATURES = AR_FEATURES + NEWS_FEATURES
    TARGET            = "target_crisis_binary"
    EPSILON           = 1e-10

    CATBOOST_PARAMS_AR = dict(
        iterations=200, depth=6, learning_rate=0.05,
        loss_function="Logloss", eval_metric="AUC",
        random_seed=42, verbose=0, early_stopping_rounds=30,
    )
    CATBOOST_PARAMS_FULL = dict(
        iterations=300, depth=7, learning_rate=0.03,
        loss_function="Logloss", eval_metric="AUC",
        random_seed=42, verbose=0, early_stopping_rounds=30,
    )


# ============================================================================
# HELPERS (identical logic to 01_train_models.py)
# ============================================================================

def generate_rolling_folds(df, cfg):
    all_starts = sorted(df["ipc_period_start"].unique())
    folds, fold_id = [], 0
    for test_start in all_starts:
        test_ts  = pd.Timestamp(test_start)
        train_end = test_ts - pd.DateOffset(months=cfg.IPC_PERIOD_MONTHS)
        train_start = train_end - pd.DateOffset(months=cfg.TRAIN_WINDOW_MONTHS)
        if train_start < cfg.MONTHLY_DATA_START:
            continue
        train_idx = df.index[(df["ipc_period_start"] >= train_start) & (df["ipc_period_start"] <= train_end)].tolist()
        test_idx  = df.index[df["ipc_period_start"] == test_ts].tolist()
        if len(train_idx) < 50 or len(test_idx) < 5:
            continue
        fold_id += 1
        folds.append({"fold_id": fold_id, "train_start": train_start,
                      "train_end": train_end, "test_start": test_ts,
                      "train_idx": train_idx, "test_idx": test_idx})
    return folds


def compute_fold_news_features(df_train, df_test, monthly_gdelt, train_end, cfg):
    baseline_start = train_end - pd.DateOffset(months=12)
    baseline = monthly_gdelt[
        (monthly_gdelt["month"] >= baseline_start) & (monthly_gdelt["month"] <= train_end)
    ].copy()
    cov_cols = [f"{t}_relative_coverage" for t in cfg.NEWS_THEMES]
    stats = baseline.groupby("district_id")[cov_cols].agg(["mean", "std"])
    stats.columns = [f"{c[0]}__{c[1]}" for c in stats.columns]

    def apply_z(df_s):
        out = df_s.copy()
        for t in cfg.NEWS_THEMES:
            c = f"{t}_relative_coverage"
            s = stats.reindex(out["district_id"])
            means = s[f"{c}__mean"].values
            stds  = np.where(s[f"{c}__std"].values < cfg.EPSILON, 1.0, s[f"{c}__std"].values)
            out[f"{t}_zscore"] = (out[c].values - means) / stds
        return out

    return apply_z(df_train), apply_z(df_test)


def shuffle_news_within_districts(df, news_features, rng):
    df_s = df.copy().reset_index(drop=True)
    for _, group_idx in df_s.groupby("district_id").groups.items():
        pos = list(group_idx)
        perm = rng.permutation(len(pos))
        df_s.loc[pos, news_features] = df_s.loc[pos, news_features].values[perm]
    return df_s


def prep_X(df_subset, features):
    X = df_subset[features].copy()
    X["ipc_period"] = X["ipc_period"].astype(str)
    return X


# ============================================================================
# SINGLE FOLD — DELTA VERSION (trains both AR and Combined on shuffled news)
# ============================================================================

def run_fold_delta(fold_info, df, monthly_gdelt, rng, cfg):
    df_train = df.loc[fold_info["train_idx"]].copy()
    df_test  = df.loc[fold_info["test_idx"]].copy()

    if len(df_train) == 0 or len(df_test) == 0:
        return np.nan, np.nan

    y_test = df_test[cfg.TARGET].values
    if len(np.unique(y_test)) < 2:
        return np.nan, np.nan

    # Fold-aware z-scores
    df_train, df_test = compute_fold_news_features(df_train, df_test, monthly_gdelt, fold_info["train_end"], cfg)

    # Shuffle news AFTER z-score recomputation (same design as 04_temporal_shuffle_test.py)
    combined = pd.concat([df_train, df_test], ignore_index=True)
    combined = shuffle_news_within_districts(combined, cfg.NEWS_FEATURES, rng)
    train_periods = df_train["ipc_period_start"].unique()
    df_train_s = combined[combined["ipc_period_start"].isin(train_periods)].copy()
    df_test_s  = combined[~combined["ipc_period_start"].isin(train_periods)].copy()

    # Validation split
    train_periods_sorted = sorted(df_train_s["ipc_period_start"].unique())
    n_val = max(1, int(len(train_periods_sorted) * cfg.VALIDATION_FRACTION))
    val_p = set(train_periods_sorted[-n_val:])
    fit_mask = ~df_train_s["ipc_period_start"].isin(val_p)
    df_fit = df_train_s[fit_mask]
    df_val = df_train_s[~fit_mask]

    y_fit = df_fit[cfg.TARGET].values
    y_val = df_val[cfg.TARGET].values

    cat_ar   = [cfg.AR_FEATURES.index("ipc_period")]
    cat_full = [cfg.COMBINED_FEATURES.index("ipc_period")]

    # AR model (uses real AR features — not shuffled)
    model_ar = CatBoostClassifier(**cfg.CATBOOST_PARAMS_AR, cat_features=cat_ar)
    model_ar.fit(prep_X(df_fit, cfg.AR_FEATURES), y_fit,
                 eval_set=(prep_X(df_val, cfg.AR_FEATURES), y_val),
                 use_best_model=True)
    prob_ar = model_ar.predict_proba(prep_X(df_test_s, cfg.AR_FEATURES))[:, 1]
    prauc_ar = float(average_precision_score(y_test, prob_ar))

    # Combined model (uses shuffled news)
    model_full = CatBoostClassifier(**cfg.CATBOOST_PARAMS_FULL, cat_features=cat_full)
    model_full.fit(prep_X(df_fit, cfg.COMBINED_FEATURES), y_fit,
                   eval_set=(prep_X(df_val, cfg.COMBINED_FEATURES), y_val),
                   use_best_model=True)
    prob_full = model_full.predict_proba(prep_X(df_test_s, cfg.COMBINED_FEATURES))[:, 1]
    prauc_full = float(average_precision_score(y_test, prob_full))

    return prauc_ar, prauc_full


# ============================================================================
# MAIN
# ============================================================================

def main():
    cfg = DeltaTestConfig()
    print("=" * 70)
    print("DELTA PERMUTATION TEST — Incremental Value of News Beyond AR")
    print("=" * 70)
    print(f"N_PERMUTATIONS : {cfg.N_PERMUTATIONS}")

    df = pd.read_parquet(cfg.DATA_FILE)
    df["ipc_period_start"] = pd.to_datetime(df["ipc_period_start"])

    monthly_gdelt = pd.read_parquet(cfg.MONTHLY_FILE)
    monthly_gdelt["month"] = pd.to_datetime(monthly_gdelt["month"])

    strict_districts = set(pd.read_csv(cfg.FILTER_FILE)["district"].tolist())
    df = df[df["district_id"].isin(strict_districts)].copy()
    print(f"  Dataset: {len(df):,} rows, {df['district_id'].nunique()} districts")

    # Observed delta from real model
    real_delta = None
    if cfg.REAL_RESULTS_FILE.exists():
        real_df = pd.read_csv(cfg.REAL_RESULTS_FILE)
        real_delta = float((real_df["full_pr_auc"] - real_df["ar_pr_auc"]).mean())
        print(f"  Observed mean delta PR-AUC: {real_delta:+.4f}")

    folds = generate_rolling_folds(df, cfg)
    print(f"  Folds: {len(folds)}")

    cfg.RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    results_path = cfg.RESULTS_DIR / "null_delta_distribution.csv"
    completed_perms, all_rows = set(), []
    if results_path.exists():
        existing = pd.read_csv(results_path)
        completed_perms = set(existing["permutation_id"].tolist())
        all_rows = existing.to_dict("records")
        print(f"  Resuming: {len(completed_perms)} permutations already done.")

    fold_col_names = [f"fold_{i+1}_delta" for i in range(len(folds))]

    print(f"\nRunning {cfg.N_PERMUTATIONS} permutations...\n")
    for perm_id in range(cfg.N_PERMUTATIONS):
        if perm_id in completed_perms:
            continue
        rng = np.random.default_rng(seed=perm_id)
        fold_deltas = []
        for fold_info in folds:
            prauc_ar, prauc_full = run_fold_delta(fold_info, df, monthly_gdelt, rng, cfg)
            fold_deltas.append(prauc_full - prauc_ar if not (np.isnan(prauc_ar) or np.isnan(prauc_full)) else np.nan)

        mean_delta = float(np.nanmean(fold_deltas))
        row = {"permutation_id": perm_id, "mean_delta": mean_delta}
        for j, val in enumerate(fold_deltas):
            row[fold_col_names[j]] = val
        all_rows.append(row)
        pd.DataFrame(all_rows).to_csv(results_path, index=False)

        deltas = np.array([r["mean_delta"] for r in all_rows], dtype=float)
        print(f"  Perm {perm_id:3d}/{cfg.N_PERMUTATIONS-1} | "
              f"delta={mean_delta:+.4f} | "
              f"null mean={np.nanmean(deltas):+.4f} +/- {np.nanstd(deltas):.4f}")

    results_df = pd.DataFrame(all_rows)
    null_deltas = results_df["mean_delta"].dropna()

    print(f"\n{'='*70}")
    print("FINAL RESULTS")
    print(f"  Null delta mean : {null_deltas.mean():+.4f}")
    print(f"  Null delta std  : {null_deltas.std():.4f}")
    print(f"  Null [min, max] : [{null_deltas.min():+.4f}, {null_deltas.max():+.4f}]")

    p_value = None
    if real_delta is not None:
        p_value = float((null_deltas >= real_delta).mean())
        print(f"  Observed delta  : {real_delta:+.4f}")
        print(f"  p-value         : {p_value:.4f}  (H0: shuffled news delta >= observed)")
        interp = "NOT significant (p > 0.05)" if p_value > 0.05 else "SIGNIFICANT (p <= 0.05)"
        print(f"  News incremental value: {interp}")

    cfg_out = {
        "n_permutations": cfg.N_PERMUTATIONS,
        "n_folds": len(folds),
        "observed_delta": real_delta,
        "null_mean_delta": float(null_deltas.mean()),
        "null_std_delta":  float(null_deltas.std()),
        "p_value": p_value,
    }
    with open(cfg.RESULTS_DIR / "config.json", "w") as f:
        json.dump(cfg_out, f, indent=2)

    print("Done.")


if __name__ == "__main__":
    main()
